name: Run cargo fmt and cargo clippy

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - feature/*
      - release/*

jobs:
  lint:
    uses: drasi-project/.github/.github/workflows/rust-lint.yaml@main