name: DevSkim

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 0 * * 0'

jobs:
  devskim:
    uses: drasi-project/.github/.github/workflows/devskim.yaml@main
