name: Scorecard supply-chain security
on:
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * 1'
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  scorecard:
    uses: drasi-project/.github/.github/workflows/scorecard.yaml@main
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

